openapi: 3.0.3

info:
  title: Wizeline Lambda Trilogy Calculator
  version: 0.1.0
  description: |
    This API invokes a calculator that invokes different approaches of lambda functions through AWS API Gateway service.
  
servers:
  - url: https://{apiId}.execute-api.{region}.amazonaws.com/{stage}/
    description: Single Purpose Lambda
    variables:
      stage:
        default: development
        description: API Stage
      region:
        default: us-east-1
        description: AWS Region
      apiId:
        default: '{API ID goes here}'
        description: API ID

paths:
  /add:
    get:
      summary: Adds two numbers
      operationId: add
      parameters:
        - name: firstNum
          in: query
          required: true
          schema:
            type: number
            example: 1
        - name: secondNum
          in: query
          required: true
          schema:
            type: number
            example: 1
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: number
                
  /subtract:
    get:
      summary: Subtracts two numbers
      operationId: subtract
      parameters:
        - name: firstNum
          in: query
          required: true
          schema:
            type: number
            example: 3
        - name: secondNum
          in: query
          required: true
          schema:
            type: number
            example: 1
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: number
                
  /multiply:
    get:
      summary: Multiply two numbers
      operationId: multiply
      parameters:
        - name: firstNum
          in: query
          required: true
          schema:
            type: number
            example: 2
        - name: secondNum
          in: query
          required: true
          schema:
            type: number
            example: 4
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: number
