openapi: 3.0.3

info:
  title: Wizeline BigFan system
  version: 0.1.0
  description: |
    This API invokes a BigFan system using APIGateway, EventBridge, SQS and Lambda services.
  
servers:
  - url: https://{apiId}.execute-api.{region}.amazonaws.com/{stage}/
    description: BigFan Transactions API
    variables:
      stage:
        default: development
        description: API Stage
      region:
        default: us-east-1
        description: AWS Region
      apiId:
        default: '{API ID goes here}'
        description: API ID

paths:
  /order:
    post:
      summary: Sends orders
      operationId: order
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                transactions:
                  type: array
                  items:
                    type: object
                    properties:
                      paymentType:
                        type: string
                        enum:
                          - debit
                          - credit
                      amount:
                        type: number
                        example: 150
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  requestId:
                    type: string
                
